### PR TITLE
Added vue3-easter-egg-trigger package

### PR DESCRIPTION
**Pull request by webdevnerdstuff**

### CODE REVIEW

**Comment by Jogai** [comment]
Project looks good. The PR includes a .history folder, can you remove that?

**Comment by webdevnerdstuff** [comment]
I thought I skipped adding that. My bad. Do you mind if I create a .gitignore to add that directory to? And a couple other regular gitignore items? Should prevent that in the future.

**Comment by Jogai** [comment]
First things first, I'm not a collaborator on this repo, (I confused this with the one from vuejs wher I am). But in my opinion, a .gitignore is not needed. Especially for something like .history, because that seems to be something from one specific tool.

**Comment by webdevnerdstuff** [comment]
I add a full .gitignore file, which should help prevent multiple situations of files that should be ignored (not just .history). Doesn't hurt to have it really, but if you really want me to, I'll remove it.

**Comment by webdevnerdstuff** [comment]
Once again I got confused thinking you were a collaborator. My bad.

**Review by Gabriel-Gotti — APPROVED** [review]

**Comment by vuesomedev** [comment]
There is no code within the repository, I think it unnecessary to have a gitignore

**Pull request merged**
